extends Node
enum player_types{war,nec,soc}
var player_type:gm.player_types=0

enum ivents{none,arena,upg_arena,boss_arena,stats_map,shop}
var enemys={
	"sk_sw":{
		"s":"res://mats/enemys/e1/enemy1.tscn",
		"i":"res://mats/imgs/icons/skelV1.png",
		"ui":"res://mats/imgs/icons/skelV1_up.png",
		},
	"sk_bo":{
		"s":"res://mats/enemys/e2/enemy.tscn",
		"i":"res://mats/imgs/icons/skel_bow.png",
		"ui":"res://mats/imgs/icons/skel_bow_up.png",
		},
	"gob_be":{
		"s":"res://mats/enemys/e3/enemy.tscn",
		"i":"res://mats/imgs/icons/X.png",
		"ui":"res://mats/imgs/icons/X.png",
		},
}
var maps={
		0:{
			"locs":{
				0:{
					"l":"res://mats/lvls/lvl1.tscn",
					"color":Color(50,200,50)
				}
			},
			"ecount":Vector2(8,12),
			"enemys":[
				"sk_sw",
				"sk_sw",
				"sk_sw",
				"sk_sw",
				"sk_sw",
				"sk_bo",
			]
		},
		1:{
			"locs":{
				0:{
					"l":"res://mats/lvls/lvl2.tscn",
					"color":Color(50,200,50)
				}
				},
			"ecount":Vector2(14,20),
			"enemys":[
				"sk_sw",
				"sk_sw",
				"sk_sw",
				"sk_bo",
				"sk_bo",
			]
		},
		2:{
			"locs":{
				0:{
					"l":"res://mats/lvls/lvl3.tscn",
					"color":Color(50,200,50)
				}
				},
			"ecount":Vector2(8,15),
			"enemys":[
				"sk_sw",
				"sk_sw",
				"gob_be",
				"gob_be",
			]
		},
	}

var bosses={
	0:[
		{
			"b":"res://mats/bosses/skel/skelboss.tscn",
			"i":"res://mats/imgs/icons/skel_boss.png"
		},
	],
	1:[
		{
			"b":"res://mats/bosses/ancient_one/boss.tscn",
			"i":"res://mats/imgs/icons/skel_boss.png"
		},
	],
	2:[
		{
			"b":"res://mats/bosses/skel/skelboss.tscn",
			"i":"res://mats/imgs/icons/skel_boss.png"
		},
	],
}

var rnd=RandomNumberGenerator.new()
var objs={}
func upd_objs():
	objs={
	"player":{
		player_types.war:{
			"img":"res://mats/imgs/warrior/Down/WarriorDownIdle.png",
			"name":"Warrior",
			"hframes":5,
			"stats":{
				"hp":3,
				"hp_rgen":0.1,
				"max_stamina":1.5,
				"regen_stamina_point":0.3,
				"def":1,
				"dmg":1,
				"crit_dmg":2,
				"%crit_dmg":0.01,
				"+%att_speed":0.3,
				"%sp":0,
				"take_area":20
				},
			"prefs":{
				"cur_hp":3000000,
				"do_roll_cost":1,
				"max_exp_start":40,
				"max_exp_sc":1,
				"run_speed":80,
				"run_scale":1,
				"roll_timer":0.4,
				"roll_speed":140,
				"roll_scale":1
				},
			},
	},
	"stats":{
		"hp":{
			"v":Vector2(1,4),
			"i":"res://mats/imgs/icons/skills/hp.png",
			"t":tr("HP")
			},
		"hp_rgen":{
			"v":Vector2(0.05,0.2),
			"i":"res://mats/imgs/icons/skills/hp_regeneration.png",
			"t":tr("HP_REGEN")
			},
		"dmg":{
			"v":Vector2(1,3),
			"i":"res://mats/imgs/icons/skills/att.png",
			"t":tr("DMG")
			},
		"crit_dmg":{
			"v":Vector2(1,5),
			"i":"res://mats/imgs/icons/skills/crit_dmg.png",
			"t":tr("CRIT_DMG")
			},
		"%crit_dmg":{
			"v":Vector2(0.05,0.1),
			"i":"res://mats/imgs/icons/skills/%crit.png",
			"t":tr("%CRIT_DMG")
			},
		"+%att_speed":{
			"v":Vector2(0.005,0.01),
			"i":"res://mats/imgs/icons/skills/+%sp_att.png",
			"t":tr("%ATT_SPEED")
			},
		"def":{
			"v":Vector2(1,2),
			"i":"res://mats/imgs/icons/skills/def.png",
			"t":tr("DEF")
			},
		"max_stamina":{
			"v":Vector2(0.2,0.5),
			"i":"res://mats/imgs/icons/skills/max_stamina.png",
			"t":tr("MAX_STAMINA_VALUE")
			},
		#"do_roll_cost":{
		#	"v":Vector2(0.2,0.5),
		#	"i":"res://mats/imgs/icons/skills/rolls.png",
		#	"t":tr("MAX_STAMINA_VALUE")
		#	},
		"regen_stamina_point":{
			"v":Vector2(0.1,0.2),
			"i":"res://mats/imgs/icons/skills/stamina_regen.png",
			"t":tr("STAMINA_REGEN_VALUE")
			},
		"%sp":{
			"v":Vector2(0.02,0.1),
			"i":"res://mats/imgs/icons/skills/speed.png",
			"t":tr("%SPEED")
			},
		"take_area":{
			"v":Vector2(2,10),
			"i":"res://mats/imgs/icons/skills/take.png",
			"t":tr("COLLECTING")
			}
		},
	"updates":{
		"the sword":{
			"i":"res://mats/imgs/icons/X.png",
			"unlocked":false,
			"t":tr("THE_SWORD_TEXT"),
			"lvls":{
				0:{"stats":{"dmg":1,"crit_dmg":1},"rare":Vector2(0,0.5),"value":40},
				1:{"stats":{"dmg":2,"$crit_dmg":0.11},"rare":Vector2(0.3,0.55),"value":40},
				2:{"stats":{"dmg":6,"crit_dmg":5},"rare":Vector2(0.55,0.8),"value":50},
				3:{"stats":{"dmg":10,"crit_dmg":9,"%crit_dmg":0.2},"rare":Vector2(0.8,1),"value":55},
				}
			},
		"armor":{
			"i":"res://mats/imgs/icons/X.png",
			"unlocked":false,
			"t":tr("ARMOR_TEXT"),
			"lvls":{
				0:{"stats":{"def":1},"rare":Vector2(0,0.05),"value":45},
				1:{"stats":{"def":1,"%sp":0.01},"rare":Vector2(0,0.05),"value":45},
				3:{"stats":{"def":4},"rare":Vector2(0.05,0.5),"value":60},
				4:{"stats":{"def":8},"rare":Vector2(0.5,1.0),"value":69},
				}
			},
		"boots":{
			"i":"res://mats/imgs/icons/X.png",
			"unlocked":false,
			"t":tr("BOOTS_TEXT"),
			"lvls":{
				0:{"stats":{"%sp":0.05},"rare":Vector2(0,0.5),"value":50},
				4:{"stats":{"%sp":0.07},"rare":Vector2(0.5,1.0),"value":100},
				}
			},
		"item1":{
			"i":"res://mats/imgs/icons/X.png",
			"unlocked":false,
			"t":tr("item1_TEXT"),
			"lvls":{
				0:{"stats":{"%sp":0.05,},"rare":Vector2(0,0.5),"value":40},
				1:{"stats":{"%sp":0.07,"hp":2},"rare":Vector2(0.5,1.0),"value":100},
				}
			}
	},
	"items":{
		"surikens":{
			"i":"res://mats/imgs/icons/X.png",
			"unlocked":false,
			"t":tr("SURIKEN_TEXT"),
			"scn":"res://mats/items/sur/sur/sur.tscn",
			"lvls":{
				0:{"stats":{
					"dmg":1,
					"crit_dmg":0,
					"%crit_dmg":0,
					"item_count":3,
					"item_spawn_time":5,
					},
				"rare":Vector2(0,0.5),
				"value":40
				},
			}
		}
	}
}
func get_item(item_name:String,lvl:int):
	var stats=objs.items[item_name].lvls[lvl]
	var s=load(objs.items[item_name].scn).instantiate()
	s.set_stats(stats)
	fnc.get_hero().get_node("lvls").add_child(s)
func _ready():
	upd_objs()
	rnd.randomize()
